### ISSUE TITLE
How to update nix json files?

### ISSUE THREAD

**Issue by wizzup** [qfpl/applied-fp-course#89]
I want to try using nixpkgs released [19.09](https://github.com/NixOS/nixpkgs/releases/tag/19.09) but can't find tool to update nix json [files](https://github.com/qfpl/applied-fp-course/tree/master/nix).

Which tool is use for this purpose?  I might just edit the manually but it doesn't seem to be the right way to do it.

**Comment by endgame** [comment]
You can test with a different nixpkgs by running something like `nix-shell --arg nixpkgs 'import <nixpkgs> {}'`.

The json files are generated by `nix-prefetch-git`, which you can gain access to via `nix-shell -p nix-prefetch-git`. I like to put an `update.bash` in `nix/` to perform those calls, but there isn't one. If you want, you could crib the [`update.bash` from `semialign-extras`](https://github.com/qfpl/semialign-extras/blob/3871f0131ad165a5cb5c990a57d7b646dc125e77/nix/update.bash) as a guide.

If you do advance the pinned packages successfully, I'll happily merge a PR.

I'll close this issue because I think I've answered your question, but feel free to reopen if you need more info.
